### PR TITLE
Update user settings to table layout

### LINKED ISSUE #231: Clear Addition
**Link to the page in the manual:**
https://manual.avolites.com/docs/next/system-settings/user-settings/#clear

**Old Text (if applicable):**
NA

**New Text:**
Clear Selected Fixtures
   Clear only selected fixtures or if no fixtures are selected all fixtures from the programmer. The default is to always clear all fixtures in the programmer. 

**Why it should be changed:**
New in V14 just adding to make sure it gets added 

**Other Information:**
Any other information

### PR DESCRIPTION
**Pull request by congoblue**
This has required using \<br\> to break lines inside tables. If this causes problems with the PDF we will have to reverse this, but it does make the user settings easier to navigate. 

Also the default settings are now shown.

Also Fixes #231

### CODE REVIEW

**Comment by Farrser** [comment]
I have attempted to check this but the PDF build is currently broken. I don't want to approve without being able to validate it at the moment because I will be doing the final v14 build soon.

I'll have a look at fixing the PDF build soon

**Comment by congoblue** [comment]
Is it possible to establish if this table formatting works in the pdf or not?

If not I will edit the previous format to be more consistent and show the default options, which it currently doesn't.

**Comment by Farrser** [comment]
@congoblue yes the PDF is working now in the `master` branch. I think this branch just needs updating and then we can run through a build to validate this works

**Comment by garethnunns** [comment]
> Is it possible to establish if this table formatting works in the pdf or not?
> 
> If not I will edit the previous format to be more consistent and show the default options, which it currently doesn't.

It will look roughly like this:
[Titan-Pre-Release-system-settings-2020-11-04-13-59-39.pdf](https://github.com/AvolitesLtd/TitanManual/files/5488197/Titan-Pre-Release-system-settings-2020-11-04-13-59-39.pdf)

**Comment by congoblue** [comment]
OK so it has just ignored the \<br\>.  Also the column widths are rather strange.
It makes it hard to read compared to the online version. I am not sure it is usable like this, what do you think?

avotest

Online version 
avotest_html

**Comment by garethnunns** [comment]
I think that's usable, I can make it but in a new line for the `<br>` otherwise

**Comment by congoblue** [comment]
If you can make it put a line break in the pdf for \<br\> that would be perfect

**Comment by garethnunns** [comment]
The commit I just added outputs like this

[Titan-Pre-Release-system-settings-2020-11-04-18-54-18.pdf](https://github.com/AvolitesLtd/TitanManual/files/5489949/Titan-Pre-Release-system-settings-2020-11-04-18-54-18.pdf)

This was the resolve for column widths: https://stackoverflow.com/questions/27219629/how-to-control-cell-width-in-pandoc-markdown-table

To test this yourself locally, you can do:

````shell
docker-compose run pdf bash
# then once the image is created:
node ../parse/pdf.js -v next -s "System Settings" --no-legal
````

**Comment by congoblue** [comment]
That looks perfect and I like the way you can make the table columns have a consistent width, it's a shame there is no way to do that (not that I can find anyway) for the online/html version, it just looks a bit messy.

Can we merge this into the master now we know it works?

**Review by Farrser — APPROVED** [review]

**Pull request merged**
