### PR TITLE
Change hubs to switches and update Art-Net example

### PR DESCRIPTION
**Pull request by congoblue**

### CODE REVIEW

**Comment by congoblue** [comment]
Seems to have failed test because I changed the images, and the new images aren't there yet?

**Review by Farrser — APPROVED** [review]

**Comment by Farrser** [comment]
Looks fine in concept just needs the test failures fixing

**Comment by congoblue** [comment]
How do I see / change the spelling list? I am not sure what is failing.

**Comment by Farrser** [comment]
If you check out the branch locally and run `npm run test` you should get a more helpful output. If it is not formatting properly you can try `npm run spellcheck` which should give you an output something like this:

Screenshot 2020-10-12 at 11 39 17

You can then either edit the files to correct the errors or edit the `.spelling` file to change the spelling list

**Review by Farrser — APPROVED** [review]

**Pull request merged**
