### PR TITLE
Update advanced-options.md

### PR DESCRIPTION
**Pull request by icke-siegen**
Added missing backslashes to properly format buttons.

### CODE REVIEW

**Comment by congoblue** [comment]
Is "Fixture Tools" a different name for "ML menu" button on some consoles? (I can't remember). If so it would be worth explaining this, in this section

**Comment by icke-siegen** [comment]
> Is "Fixture Tools" a different name for "ML menu" button on some consoles? (I can't remember). If so it would be worth explaining this, in this section

I don't really know - it was written like this before. Maybe on some very old consoles. I'd say JB would know.

**Comment by icke-siegen** [comment]
Screenshot from the v3.0 manual for the Tiger Touch:

image

**Comment by icke-siegen** [comment]
And from an official product image

image

**Comment by congoblue** [comment]
Looks like it is only on the Tiger Touch mk1. I think I would remove the "Fixture Tools" text for clarity - I doubt if there are many TT1 consoles with the hardware update needed to run the latest Titan versions.

**Comment by Farrser** [comment]
Annoyingly I think this is on some upgraded TT1s and Experts so it probably needs to stay

**Review by Farrser — APPROVED** [review]

**Pull request merged**
